spring:
  application:
    name: market-monitor-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/market_monitor
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin
  
# App Configuration (mapped to ServiceConfig)
app:
  jwt-secret: your-secret-key-here-make-it-long-and-secure-in-production
  jwt-expiration: 86400000 # 24 hours in milliseconds
  
  alpha-vantage-api-key: IU9W74WEF0DEWLCF # Replace with your actual API key
  alpha-vantage-base-url: https://www.alphavantage.co/query
  alpha-vantage-delay: 15 # 15-minute delay for free tier
  
  # CoinGecko Configuration
  coin-gecko-base-url: https://api.coingecko.com/api/v3
  coin-gecko-delay: 6 # 6 seconds delay for free tier (10 calls per minute)
  
  # Market Data Symbols Configuration
  alpha-vantage-symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - TSLA
    - META
    - NVDA
    - NFLX
    - JPM
    - JNJ
    - V
    - PG
    - UNH
    - HD
    - MA
    - DIS
    - PYPL
    - BAC
    - ADBE
    - CRM
  
  coin-gecko-symbols:
    - BTC
    - ETH
    - BNB
    - ADA
    - SOL
    - XRP
    - DOT
    - DOGE
    - AVAX
    - MATIC
    - LINK
    - UNI
    - LTC
    - XLM
    - ATOM
    - XMR
    - ALGO
    - VET
    - FIL
    - TRX
  
  server-port: 8092
  server-context-path: /api
  
# Server Configuration
server:
  port: 8092
  servlet:
    context-path: /api

# Logging
logging:
  level:
    com.puentenet: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 